Updated 'trash' to support emptying the trash via AppleScript, if available.

diff --git a/trash b/trash
--- a/trash
+++ b/trash
@@ -105,26 +105,39 @@ if [ $# -gt 0 ]; then
 		# see if the user requested to empty the trash contents
 		elif [ "$1" = "-e" ]; then
 			shift
-			if $verbose; then v="-v"; fi
-			# confirm that the user wants to empty the trash
-			printf "Are you sure you want to empty the trash (this cannot be undone)? "
-			read confirm
-			if [ "$confirm" = "y" ]; then
-				printf "Emptying trash...\n"
-				# delete the contents of user's .Trash folder
-				find "/Users/${user}/.Trash" -depth 1 ! -depth 0 -print0 | xargs -0 rm $v -r
-				# delete the contents of the volume-specific .Trashes folders
-				for file in /Volumes/*; do
-					if [ -d "$file" ]; then
-						folder="${file}/.Trashes/${uid}"
-						if [ -d "$folder" ]; then
-							find "$folder" -depth 1 ! -depth 0 -print0 | xargs -0 rm $v -r
+			# determine if we can tell Finder to empty trash via AppleScript
+			if have_scriptable_finder; then
+				if $verbose; then printf "Telling Finder to empty trash... "; fi
+				if /usr/bin/osascript -e "tell application \"Finder\" to empty trash" ; then
+					if $verbose; then printf "Done.\n"; fi
+					exit
+				else
+					if $verbose; then printf "ERROR!\n"; fi
+					exit 1
+				fi
+			# if Finder isn't scriptable, we'll manually empty the trash ourselves
+			else
+				if $verbose; then v="-v"; fi
+				# confirm that the user wants to empty the trash
+				printf "Are you sure you want to empty the trash (this cannot be undone)? "
+				read confirm
+				if [ "$confirm" = "y" ]; then
+					printf "Emptying trash...\n"
+					# delete the contents of user's .Trash folder
+					find "/Users/${user}/.Trash" -depth 1 ! -depth 0 -print0 | xargs -0 rm $v -r
+					# delete the contents of the volume-specific .Trashes folders
+					for file in /Volumes/*; do
+						if [ -d "$file" ]; then
+							folder="${file}/.Trashes/${uid}"
+							if [ -d "$folder" ]; then
+								find "$folder" -depth 1 ! -depth 0 -print0 | xargs -0 rm $v -r
+							fi
 						fi
-					fi
-				done
-				printf "Done.\n"
+					done
+					printf "Done.\n"
+				fi
+				exit
 			fi
-			exit
 		# see if the user requested to securely empty the trash contents
 		elif [ "$1" = "-s" ]; then
 			shift
